github_actions:
- changed-files:
  - any-glob-to-any-file: '.github/**/*'

REDIS:
- changed-files:
  - any-glob-to-any-file: 'tests/test_redis.py'
  - any-glob-to-any-file: 'openfoodfacts/redis.py'

images:
- changed-files:
  - any-glob-to-any-file: 'openfoodfacts/images.py'
  - any-glob-to-any-file: 'tests/​test_images.py'

OCR:
- changed-files:
  - any-glob-to-any-file: 'tests/​test_ocr.py'
  
tests:
- changed-files:
  - any-glob-to-any-file: 'tests/test_utils.py'
  - any-glob-to-any-file: 'tests/​test_api.py'
  - any-glob-to-any-file: 'tests/​test_ocr.py'
  - any-glob-to-any-file: 'tests/​test_redis.py'
  - any-glob-to-any-file: 'tests/​test_images.py'
  - any-glob-to-any-file: 'tests/​test_api_config.py'

utils:
- changed-files:
  - any-glob-to-any-file: 'openfoodfacts/utils.py'
  - any-glob-to-any-file: 'tests/test_utils.py'

dependencies:
- changed-files:
  - any-glob-to-any-file: 'poetry.lock'

documentation:
- changed-files:
  - any-glob-to-any-file: 'handle_taxonomies.md'
  - any-glob-to-any-file: 'usage.md'
